### ISSUE TITLE
Videos Fail

### ISSUE THREAD

**Issue by Karr** [MicrosoftDocs/security#1]
Can someone please fix the videos on this page.  Every one of them fails in both Chrome and Edge.  Didn't bother with other browsers.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f22ec8eb-bae1-49b5-5a1a-d00772bad3c1
* Version Independent ID: 2b9b10e4-9dc7-3d09-b297-c05afe71ed2d
* Content: [Microsoft Security Best Practices module: Privileged administration](https://docs.microsoft.com/en-us/security/compass/administration-videos-and-decks)
* Content Source: [compass/administration-videos-and-decks.md](https://github.com/MicrosoftDocs/security/blob/main/compass/administration-videos-and-decks.md)
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
This issue appears to be fixed. Closing PR.
