### ISSUE TITLE
Abuseip or AbuseIPDB?

### ISSUE THREAD

**Issue by jeminjeon** [MicrosoftDocs/security#10]
Hello @JoeDavies-MSFT,

Correct me if I'm wrong...

Skimming through your amazing documentation, I found **Abuseip[dot]com** under the [Verify IP addresses to attackers/campaigns](https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-phishing#verify-ip-addresses-to-attackerscampaigns) section.

May I check if you intended to put [AbuseIPDB](https://www.abuseipdb.com/) here?

Thank you for your efforts for Incident response playbooks documentation!

\- Jemin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daae9c8b-a9c6-01a7-1072-faaab97793bf
* Version Independent ID: 08cb659e-3295-e2df-4d9b-e0f426e238e7
* Content: [Phishing investigation](https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-phishing)
* Content Source: [compass/incident-response-playbook-phishing.md](https://github.com/MicrosoftDocs/security/blob/main/compass/incident-response-playbook-phishing.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@jeminjeon I have corrected this error. Thanks so much for letting un know.
