### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by robneill** [MicrosoftDocs/security#11]
You may want to check your spelling of the word "Splunk"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afa07a3b-22b0-fc02-2389-24e7cad75174
* Version Independent ID: 955631a2-94bd-8c9c-bf0c-f3ea08ff50f1
* Content: [Password spray investigation](https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-password-spray)
* Content Source: [compass/incident-response-playbook-password-spray.md](https://github.com/MicrosoftDocs/security/blob/main/compass/incident-response-playbook-password-spray.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@robneill  Checked and corrected. Thanks so much for letting us know.
