### ISSUE TITLE
Associated MCRA workshop videos

### ISSUE THREAD

**Issue by ejazr83** [MicrosoftDocs/security#13]
Is it possible to link or create MCRA videos that would present these slides. The CISO compass videos are quite helpful to understand these concepts in a better way than just the speakers notes.

Although the speaker notes are also quite detailed and is very good. IT would be helpful if we could have a few videos presenting these MCRA PPTs. It might be something that is already in the pipeline so in that case, feel free to ignore this feedback.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5b0f5d1-01c7-baad-0540-24cebe0b5b84
* Version Independent ID: f759fd8d-ce47-4a6f-27c5-f38003cd3464
* Content: [Microsoft Cybersecurity Reference Architectures - Security documentation](https://docs.microsoft.com/en-us/security/cybersecurity-reference-architecture/mcra)
* Content Source: [security-docs/cybersecurity-reference-architecture/MCRA.md](https://github.com/MicrosoftDocs/security/blob/main/security-docs/cybersecurity-reference-architecture/MCRA.md)
* Service: **security**
* GitHub Login: @MarkSimos
* Microsoft Alias: **mas**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
