### ISSUE TITLE
Broken/Outdated? link for Trusted Root CA application

### ISSUE THREAD

**Issue by ariccy** [MicrosoftDocs/security#137]
The link of root CA application [https://aka.ms/rootcertapply](https://aka.ms/rootcertapply) which redirects to [CA Trusted Root Program Application-2018.pdf](https://gallery.technet.microsoft.com/Trusted-Root-Program-abc0082e/file/200888/2/CA%20Trusted%20Root%20Program%20Application-2018.pdf) is now redirecting to [Browse code samples](https://docs.microsoft.com/samples/browse/?redirectedfrom=TechNet-Gallery) eventually.
What is the correct link for root application now?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a89d1f2-b584-a6ce-711e-45a84b9efd0e
* Version Independent ID: 09b2b395-f083-dd0b-8113-95c90701814d
* Content: [New CA application - Microsoft Trusted Root Program](https://docs.microsoft.com/en-us/security/trusted-root/new-ca-application#feedback)
* Content Source: [trusted-root-docs/new-ca-application.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/new-ca-application.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by tahmad2** [comment]
#please-close

**Comment by ariccy** [comment]
The page has been updated and the application is currently closed.

**Comment by ariccy** [comment]
The page has been updated and the application is currently closed.
