### ISSUE TITLE
This is Amazing!

### ISSUE THREAD

**Issue by HariKSamineni** [MicrosoftDocs/security#14]
I am so impressed by the knowledge shared that I am determined to take a deep dive in Azure Security Center and Microsoft Defender. I just wanted to give my feedback after going  through those videos. Thank you so much! Hari Krishna.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee46b0b-ac67-ac24-7a47-8ed7ab1a4f79
* Version Independent ID: 832a4d07-7564-3bfb-5b21-8544d79b6469
* Content: [Microsoft Security Best Practices module: Security operations](https://docs.microsoft.com/en-us/security/compass/security-operations-videos-and-decks)
* Content Source: [compass/security-operations-videos-and-decks.md](https://github.com/MicrosoftDocs/security/blob/main/compass/security-operations-videos-and-decks.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
Thank you for your feedback! #please-close
