### ISSUE TITLE
Steps 2 and 3 of 3 link back to the same document

### ISSUE THREAD

**Issue by matthewjlevy** [MicrosoftDocs/security#140]
Hi Docs team, the links in the "[Whats in this solution](https://docs.microsoft.com/en-us/security/zero-trust/integrate-saas-apps#whats-in-this-solution)" section for steps 2 and 3 both link back to this same document (https://docs.microsoft.com/en-us/security/zero-trust/integrate-saas-apps)

Not sure that is intented, but I would assume there are more steps to find for
"Create Microsoft Defender for Cloud Apps policies" perhaps this [link](https://docs.microsoft.com/en-us/defender-cloud-apps/control-cloud-apps-with-policies) ?
and then "Deploy information protection for SaaS apps" should point to [this perhaps](https://docs.microsoft.com/en-us/microsoft-365/security/office-365-security/mcas-saas-access-policies?view=o365-worldwide#tune-protection-for-specific-saas-apps)?

Here's a screenshot of the two links I'm refering to:
![image](https://user-images.githubusercontent.com/27995471/189109397-0f961718-1e56-4345-b6ad-af2fb681c8fd.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 87bc2ee3-48b0-f4bb-90e9-8784249e99f9
* Version Independent ID: 87bc2ee3-48b0-f4bb-90e9-8784249e99f9
* Content: [Integrate SaaS apps for Zero Trust with Microsoft 365](https://docs.microsoft.com/en-us/security/zero-trust/integrate-saas-apps)
* Content Source: [zero-trust/integrate-saas-apps.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/integrate-saas-apps.md)
* Service: **security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by mjcaparas** [comment]
Thank you! I've created a PR to fix this issue.
