### ISSUE TITLE
Root no pc

### ISSUE THREAD

**Issue by kaiycoul** [MicrosoftDocs/security#146]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f6bd8a54-83da-71b2-5302-7135bdd4b673
* Version Independent ID: ab647c6d-f41b-00f3-9fae-bdcf0ca8a486
* Content: [June 2020 Deployment Notice - Microsoft Trusted Root Program](https://learn.microsoft.com/en-us/security/trusted-root/2020/june2020)
* Content Source: [trusted-root-docs/2020/June2020.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/2020/June2020.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by tahmad2** [comment]
Looked through the link provided in the issue, and I was unable to determine what the issue here was. June 2020 deployment notice is present, closing this issue. #please-close
