### ISSUE TITLE
What is a panacea?

### ISSUE THREAD

**Issue by AndrewBlumhardt** [MicrosoftDocs/security#152]
I'll bet most people don't know what "panacea" means, especially with an international audience. Why not just say technology is not the only solution?

The first rule is ruining the ROI. What about when the attacker is not financially motivated? Like a nation state or ATP? It seems like this approach may be outdated and lower on the list.

Rule 8 refers to air-gaps leading to a false sense of security. Valid point but air gap usage is not common these days. I am not certain if it belongs in the top 10. A more modern rule may be something like, don't try to do it all alone (don't work in isolation). Find ways to leverage the knowledge of others using vendors, community, and crowdsourcing solutions. Relying on our own people to create rules, record IOCs, tune alerts, and hunt for gaps is ineffective. I think this is already covered in Rule 6. 

No mention of automation or response time. No mention of MFA and conditional access.

A few more ideas:

Automation never sleeps and attackers take advantage or nights, holidays, and times of crisis.
Prevention is far more valuable than detection and response.
You can't investigate what you don't log and you can't restore what you don't back up.
Encryption is meaningless when files are unencrypted. Files are unencrypted (vulnerable) at read, update, and creation. 
If you don't lock it down, users will assume that it is allowed.
Prioritization should be based on an attack framework like MITRE. 
Security is too broad for any one person. No security solution can cover everything. Security teams rely on a wide range of solutions. Maintaining expertise on the entire stack is an unrealistic expectation for one person.
Treat your security and admin staff well. They are hard to find, expensive to train, and a revolving door is expensive and risky. Current and past disgruntled admins are a major risk.

Thanks, Andrew

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a71b8b4b-1ca7-db00-3080-eae2566e1f36
* Version Independent ID: a71b8b4b-1ca7-db00-3080-eae2566e1f36
* Content: [The immutable laws of security](https://learn.microsoft.com/en-us/security/compass/ten-laws-of-security)
* Content Source: [compass/ten-laws-of-security.md](https://github.com/MicrosoftDocs/security/blob/main/compass/ten-laws-of-security.md)
* Service: **security**
* Sub-service: **security-fundamentals**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Thanks for the feedback. We will review with the team. #please-close

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
