### ISSUE TITLE
Correct Inappropriate Link

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/security#156]
Below the Enforce a minimum version of TLS, is a link to Prevent Shared Key..., which is a repeat from the section above, this link should point to something about TLS

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0636fa6-c28e-e894-5e70-ddf0a7348de0
* Version Independent ID: b0636fa6-c28e-e894-5e70-ddf0a7348de0
* Content: [Apply Zero Trust principles to Storage in Azure](https://learn.microsoft.com/en-us/security/zero-trust/azure-infrastructure-storage)
* Content Source: [zero-trust/azure-infrastructure-storage.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/azure-infrastructure-storage.md)
* Service: **security**
* GitHub Login: @sikovatc
* Microsoft Alias: **sikovatc**

**Comment by sikovatc** [comment]
Good catch! Will correct. Thank you.

**Comment by JoeDavies-TechWriter** [comment]
This has been corrected. Thanks for letting us know.
