### ISSUE TITLE
Correlate Text to diagram

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/security#157]
Step 3 has some numbers on the diagrams, but the text does not include any numbers so it is difficult to determine which paragraph is associated with a numbered line on the diagram. Please add some explicit numbering to decrease my confusion.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0636fa6-c28e-e894-5e70-ddf0a7348de0
* Version Independent ID: b0636fa6-c28e-e894-5e70-ddf0a7348de0
* Content: [Apply Zero Trust principles to Storage in Azure](https://learn.microsoft.com/en-us/security/zero-trust/azure-infrastructure-storage)
* Content Source: [zero-trust/azure-infrastructure-storage.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/azure-infrastructure-storage.md)
* Service: **security**
* GitHub Login: @sikovatc
* Microsoft Alias: **sikovatc**

**Comment by sikovatc** [comment]
Thanks for the feedback, Dean! I will edit that to make it clearer.

**Comment by JoeDavies-TechWriter** [comment]
Hi Dean, This has been corrected with an updated version of the diagram and associated table. Please let us know if you have any additional comments.
