### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/security#158]
The top of this page includes a nice table describing how each zero trust principle will be met, it would be helpful to have  a similar table on each of the other pages in this section about ZTA for IAAS infrastructure. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b0f08525-6130-5350-7983-18c379555ac1
* Version Independent ID: b0f08525-6130-5350-7983-18c379555ac1
* Content: [Apply Zero Trust principles to spoke virtual network in Azure](https://learn.microsoft.com/en-us/security/zero-trust/azure-infrastructure-iaas)
* Content Source: [zero-trust/azure-infrastructure-iaas.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/azure-infrastructure-iaas.md)
* Service: **security**
* GitHub Login: @brsteph
* Microsoft Alias: **bstephenson**

**Comment by JoeDavies-TechWriter** [comment]
Hi Dean. All four articles now have consistent Zero Trust mapping tables, both at the article and step level. Thanks for letting us know.
