### ISSUE TITLE
Federate with on-premises should be synchronize on-prem to AAD

### ISSUE THREAD

**Issue by wilbug1git1** [MicrosoftDocs/security#16]
In section 1 this document states Cloud identity federates with on-premises identity systems and also says Connect all of your users to Azure AD and federate with on-premises identity systems.  This implies leveraging AD FS instead of leveraging AAD as the authoritative source for identities.  

Both of these should says synchronize onprem identities to Azure AD and not refer to federation.  
 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf822ed1-8fb0-d02c-3677-0afd1e19f553
* Version Independent ID: ca142bdc-5c0a-3ed1-8bce-a97c34a62e72
* Content: [Securing identity with Zero Trust](https://docs.microsoft.com/en-us/security/zero-trust/identity)
* Content Source: [zero-trust/identity.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/identity.md)
* Service: **security**
* GitHub Login: @garycentric
* Microsoft Alias: **v-gmoor**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
