### ISSUE TITLE
Steps incorrect 

### ISSUE THREAD

**Issue by CookeDanny** [MicrosoftDocs/security#18]
Within [https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment#azure-ad-users-and-groups](url)

Documentation has steps to add a Secure Workstation Administrator twice (assume one should be a user but both have same privileges)

Create your device user by following the steps in the create user tutorial.

Enter:

Name - Secure Workstation Administrator <--
User name - secure-ws-user@contoso.com
Directory role - Limited administrator and select the Intune Administrator role.
Usage Location - United Kingdom
Select Create.

Create your device administrator user.

Enter:

Name - Secure Workstation Administrator -<<
User name - secure-ws-admin@contoso.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc109e7-e2ad-6e3c-598d-36876b40dbfd
* Version Independent ID: da56e91b-41ca-2c29-0e8c-bc4d2a36a748
* Content: [Deploying a privileged access solution](https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment)
* Content Source: [compass/privileged-access-deployment.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-deployment.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
