### ISSUE TITLE
incorrect product name

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/security#180]
there is an incorrect statement: 
Defender for Cloud Apps (previously known as Microsoft Defender for Cloud Apps), should be Defender for Cloud Apps (previously known as Microsoft Cloud App Security)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: caf2ecd4-a7c3-5b7e-2200-4ea928d47c82
* Version Independent ID: caf2ecd4-a7c3-5b7e-2200-4ea928d47c82
* Content: [Microsoft DART ransomware approach and best practices](https://learn.microsoft.com/en-us/security/compass/incident-response-playbook-dart-ransomware-approach)
* Content Source: [compass/incident-response-playbook-dart-ransomware-approach.md](https://github.com/MicrosoftDocs/security/blob/main/compass/incident-response-playbook-dart-ransomware-approach.md)
* Service: **microsoft-365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears this issue is fixed. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
