### ISSUE TITLE
Minor grammar error?

### ISSUE THREAD

**Issue by josamontiel** [MicrosoftDocs/security#190]
In the ‘Do no harm’ bullet point under the **Incident response process** section. 

“Confirm that your response is designed and executed in a way that avoids loss of data, loss of business-critical functionality, and loss of evidence. Avoid decisions `that` can damage your ability to create forensic timelines, identify root cause, and learn critical lessons.”

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16b8bcea-c43f-0f8f-1d0d-30bc2106e365
* Version Independent ID: 16b8bcea-c43f-0f8f-1d0d-30bc2106e365
* Content: [Incident response overview](https://learn.microsoft.com/en-us/security/operations/incident-response-overview)
* Content Source: [operations/incident-response-overview.md](https://github.com/MicrosoftDocs/security/blob/main/operations/incident-response-overview.md)
* Service: **microsoft-365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by joe-davies-affirm** [comment]
This is fixed. Thanks so much for letting us know.
