### ISSUE TITLE
Duplicate objective in list

### ISSUE THREAD

**Issue by MixolydianV** [MicrosoftDocs/security#199]
In the Zero trust objectives list (https://learn.microsoft.com/en-us/security/zero-trust/deploy/data#data-zero-trust-deployment-objectives) Objective III is missing, and Objective I is listed twice:

![image](https://github.com/MicrosoftDocs/security/assets/6654396/8d474624-c0cc-4841-8b26-3054329cc422)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 79343709-0480-e6d0-bf6f-71d36cd24eb3
* Version Independent ID: 05216694-6a9c-6971-419f-ec134a954e58
* Content: [Secure data with Zero Trust](https://learn.microsoft.com/en-us/security/zero-trust/deploy/data)
* Content Source: [zero-trust/deploy/data.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/deploy/data.md)
* Service: **security**
* GitHub Login: @garycentric
* Microsoft Alias: **v-gmoor**

**Comment by cabailey** [comment]
Thanks for flagging - now fixed
#please-close
