### ISSUE TITLE
Video Links

### ISSUE THREAD

**Issue by henrypi73** [MicrosoftDocs/security#2]
Hi There, all links to the videos are broken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6b3644b-6d56-1891-e580-75e9647fb4b3
* Version Independent ID: ea2eab3a-07f2-a1cd-6e50-a945373c64c9
* Content: [Chief Information Security Officer (CISO) Workshop, Module 1: Microsoft Cybersecurity Briefing - Security documentation](https://docs.microsoft.com/en-us/security/ciso-workshop/ciso-workshop-module-1)
* Content Source: [ciso-workshop/ciso-workshop-module-1.md](https://github.com/MicrosoftDocs/security/blob/main/ciso-workshop/ciso-workshop-module-1.md)
* Service: **o365-seccomp**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. This issue appears to be fixed. #please-close
