### ISSUE TITLE
feedback as a cirt persona

### ISSUE THREAD

**Issue by iotmaker1** [MicrosoftDocs/security#203]
Informative post with lot of detections in one single place to monitor token compromise/theft. The response actions using GraphAPI for containment are extremely useful for IDM teams.
Some feedback from a cirt incident response analyst persona is a little difficult to use.
- For detections a workbook dashbaord or sentinel yaml alert would help make detection process much faster for cirt.
- A reference to Graph explorer and obtaining various id's (object id vs email authentication id) for api calls would be helpful to generate logic app automation to go with sentinel alerts.
Just my 2 cents trying out some of the detections and response actions in the post to make it more effective.

Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a253cbed-7f86-54fa-c4d8-fb3062e049a4
* Version Independent ID: a253cbed-7f86-54fa-c4d8-fb3062e049a4
* Content: [Token theft playbook](https://learn.microsoft.com/en-us/security/operations/token-theft-playbook)
* Content Source: [operations/token-theft-playbook.md](https://github.com/MicrosoftDocs/security/blob/main/operations/token-theft-playbook.md)
* Service: **security**
* Sub-service: **security-fundamentals**
* GitHub Login: @janicericketts
* Microsoft Alias: **jricketts**

**Comment by janicericketts** [comment]
#please-close
