### ISSUE TITLE
Some instructions are outdated

### ISSUE THREAD

**Issue by vmwaredinesh** [MicrosoftDocs/security#21]
[Some of the steps are outdated. For example "search-mailbox" is deprecated. Deleting emails step should be updated with new threat explorer option. It is much better and accurate results to search and delete emails quickly ]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daae9c8b-a9c6-01a7-1072-faaab97793bf
* Version Independent ID: 08cb659e-3295-e2df-4d9b-e0f426e238e7
* Content: [Phishing investigation](https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-phishing)
* Content Source: [compass/incident-response-playbook-phishing.md](https://github.com/MicrosoftDocs/security/blob/main/compass/incident-response-playbook-phishing.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
