### ISSUE TITLE
Hyperlink points to a non-existent page

### ISSUE THREAD

**Issue by chriccomscore** [MicrosoftDocs/security#213]
This hyperlink on your page, leads to a non-existent page.
 https://aka.ms/webtrustauditors.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0d56bc05-3a7e-65a8-d188-c87e6ec411f4
* Version Independent ID: 8d126e63-2c0d-446b-5e49-410ac7c0bcd4
* Content: [Audit Requirements - Microsoft Trusted Root Certificate Program](https://learn.microsoft.com/en-us/security/trusted-root/audit-requirements)
* Content Source: [trusted-root-docs/Audit-Requirements.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/Audit-Requirements.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by tahmad2** [comment]
WebTrust Auditors link appears to be working and directs to the WebTrust seal program page. Closing this issue. #please-close
