### ISSUE TITLE
Abandonment of on-prem and a Marketing pitch?

### ISSUE THREAD

**Issue by lastpick72** [MicrosoftDocs/security#22]
[Enter feedback here]
A misleading document that comes across as a marketing pitch for cloud services. The article suggests that one of the reasons for its retirement is the complexity. While true that the complexity is high, the *New model extends on the existing ESAE model by adding additional complexity that has no prescriptive steps listed for implementation. Additionally, no recognition is given to the fact that most corporations will continue to rely on the hybrid deployment of on-prem and cloud. Switching to a zero-trust model is simply not feasible. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3d6e6fb-c597-74e3-d98c-bb233918bd9c
* Version Independent ID: 17975324-a019-4ee0-5792-b069cff936c5
* Content: [Enhanced Security Admin Environment (ESAE) architecture mainstream retirement](https://docs.microsoft.com/en-us/security/compass/esae-retirement)
* Content Source: [compass/esae-retirement.md](https://github.com/MicrosoftDocs/security/blob/main/compass/esae-retirement.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Organizations can still choose to deploy ESAE. #please-close
