### ISSUE TITLE
Security Adoption Resources

### ISSUE THREAD

**Issue by sama-ndongong** [MicrosoftDocs/security#226]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea121fbb-872a-d704-3f3c-c859b8fba776
* Version Independent ID: ea121fbb-872a-d704-3f3c-c859b8fba776
* Content: [Security Adoption Resources - Security documentation](https://learn.microsoft.com/en-gb/security/ciso-workshop/adoption)
* Content Source: [ciso-workshop/adoption.md](https://github.com/MicrosoftDocs/security/blob/main/ciso-workshop/adoption.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
