### ISSUE TITLE
Error in link

### ISSUE THREAD

**Issue by BenjiSec** [MicrosoftDocs/security#23]
[Enter feedback here]
Hi,

There is error in link for Investigate incidents with Azure Sentinel. Hyperlink is "https://docs.microsoft.com/en-us/azure/sentinel/tutorial-investigate-cases_" but it should be without underscore (_) - "https://docs.microsoft.com/en-us/azure/sentinel/tutorial-investigate-cases"

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 302b754f-4e1a-d0fe-d88e-b8b6b9d208b3
* Version Independent ID: 5c2f524f-7c02-5c86-ddff-7190219987dc
* Content: [Incident response overview](https://docs.microsoft.com/en-gb/security/compass/incident-response-overview)
* Content Source: [compass/incident-response-overview.md](https://github.com/MicrosoftDocs/security/blob/main/compass/incident-response-overview.md)
* Product: **m365-security**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears this issue has been fixed. #please-close
