### ISSUE TITLE
konsep zero trusth

### ISSUE THREAD

**Issue by fatihjibril** [MicrosoftDocs/security#235]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 2c36a952-bd35-13b3-3cff-5af7b9676442
* Version Independent ID: 2c36a952-bd35-13b3-3cff-5af7b9676442
* Content: [What is Zero Trust?](https://learn.microsoft.com/en-us/security/zero-trust/zero-trust-overview)
* Content Source: [zero-trust/zero-trust-overview.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/zero-trust-overview.md)
* Service: **security**
* GitHub Login: @mjcaparas
* Microsoft Alias: **macapara**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. We are unclear about your feedback. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
