### ISSUE TITLE
Applying for Microsoft-compatible FIDO2 security key vendor

### ISSUE THREAD

**Issue by LinVince** [MicrosoftDocs/security#24]
Hi Microsoft,

We (WiSECURE Technologies) have filled out the form to be a FIDO2 security key. However, we have not got any response or feedback informing us of the process. We do not know whether it has been accepted and processed or not.

We would appreciate it if any information could be given so that we know how it goes. 

Best wishes,
Vince

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 55b86493-753f-4a93-2d96-1e7d5fd19117
* Version Independent ID: 0c5bcb60-c201-18fa-175f-8d5a1eee4034
* Content: [Become a Microsoft-Compatible FIDO2 Security Key Vendor](https://docs.microsoft.com/en-us/security/zero-trust/isv/fido2-hardware-vendor)
* Content Source: [zero-trust/isv/fido2-hardware-vendor.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/isv/fido2-hardware-vendor.md)
* Service: **security**
* GitHub Login: @knicholasa
* Microsoft Alias: **nichola**

**Comment by knicholasa** [comment]
Hi @LinVince ,  Someone from my team should be reaching out to you. Let me know if you do not hear from them. Closing this issue for now.

**Comment by TerryLanfear** [comment]
#please-close

**Comment by mmacy** [comment]
@TerryLanfear It looks like PR comment automation is not enabled on this repo, so `#please-close` isn't functional.

A repo owner has to either manually close them or enable repo comment automation. I believe that if you enable comment automation, you'll still need to manually close these (or, post-enable, issue `#please-close` comments in each).

Cc: @knicholasa @chrischiedo
