### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by sedelrio** [MicrosoftDocs/security#25]
In the last days the links for each of the ZT Pillars are broken. While we can go the menu and find the information, those links were working a few days ago

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 624b3329-cc27-fe94-e6ed-d13ef4f659b2
* Version Independent ID: d603f3e6-bb85-ff8f-d639-415b2b149a6d
* Content: [Building Zero Trust Architecture](https://docs.microsoft.com/es-es/security/zero-trust/)
* Content Source: [zero-trust/index.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/index.md)
* Service: **security**
* GitHub Login: @garycentric
* Microsoft Alias: **v-gmoor**

**Comment by knicholasa** [comment]
Thank you for noticing, the change was intentional since there are now multiple options for each pillar. (That is, deployment but also integration guidance).
