### ISSUE TITLE
New RaMP guidance and managing on-premises AD env

### ISSUE THREAD

**Issue by itspramod21** [MicrosoftDocs/security#27]
[Enter feedback here]
As part of Securing Privileged Access (based on new [RaMP guidance] (https://docs.microsoft.com/en-us/security/compass/privileged-access-devices)), which I felt is more focused on managing cloud services/ workloads running on Azure.

I have the following questions:

1. Does PAW devices still support managing on-premises AD env?

2. What are the supported authentication methods to RDP to on-premises servers/ DCs from PAW device? I suppose one can use Windows Hello for logging in to the PAW device itself?

3. What is the story on Azure PAW or Azure Shielded VMs in place of physical PAW?

Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c37910f2-b54e-53e5-4762-639d542deb84
* Version Independent ID: 179dd0af-e9cf-ba49-d6fb-df474af11f5e
* Content: [Why are privileged access devices important](https://docs.microsoft.com/en-us/security/compass/privileged-access-devices)
* Content Source: [compass/privileged-access-devices.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-devices.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
