### ISSUE TITLE
Spelling mistake - slide 7, "Protect Admins to strengthen **privielged** access security"

### ISSUE THREAD

**Issue by jfang88** [MicrosoftDocs/security#29]
Privileged instead of privielged

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afc9c819-8cc6-9ed4-09b0-61c297149e71
* Version Independent ID: cd5ef557-b6d7-39ed-ce74-a9597ef5390d
* Content: [Human-operated ransomware](https://docs.microsoft.com/en-us/security/compass/human-operated-ransomware)
* Content Source: [compass/human-operated-ransomware.md](https://github.com/MicrosoftDocs/security/blob/main/compass/human-operated-ransomware.md)
* Product: **m365-security**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears this issue has been fixed. #please-close
