### ISSUE TITLE
missing Privileged Administration from Best Practices main page

### ISSUE THREAD

**Issue by houey** [MicrosoftDocs/security#3]
[Enter feedback here]
The main page here: https://docs.microsoft.com/en-us/security/compass/compass. 
is missing the link to "Privileged Administration" as seen in the menu.  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 22437901-f957-993d-82ba-22f2b019db1c
* Version Independent ID: a70037b8-ccc1-533e-c948-e2b511931bf7
* Content: [Microsoft Security Best Practices](https://docs.microsoft.com/en-us/security/compass/compass)
* Content Source: [compass/compass.md](https://github.com/MicrosoftDocs/security/blob/main/compass/compass.md)
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. This issue appears to be fixed. #please-close
