### ISSUE TITLE
Current

### ISSUE THREAD

**Issue by JoeBrunsTR** [MicrosoftDocs/security#31]
Does it look like https://docs.microsoft.com/en-us/security/trusted-root/release-notes has been neglected for updates or is it just me?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f49f89a-c1ac-60ae-b112-a314da7c2c01
* Version Independent ID: d1111d9a-28b1-7a62-2471-9b962c926b51
* Content: [Release notes - Microsoft Trusted Root Certificate Program](https://docs.microsoft.com/en-us/security/trusted-root/release-notes)
* Content Source: [trusted-root-docs/Release-Notes.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/Release-Notes.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears this issue is now fixed. #please-close
