### ISSUE TITLE
Poorly organized

### ISSUE THREAD

**Issue by over2under3** [MicrosoftDocs/security#33]
[Enter feedback here]
While the intent of this document is needed, it is VERY POORLY organize and seems quite scattered. The document doesn't explicitly state which configurations should be done on regular workstations and which should be performed on PAWs/Specialized systems. An example would be URL restrictions. 

Also some of the directions do not reflect accurate links to download scripts and contains outdated directions from what's in the Azure portal.

Overall this document has created quite a bit of confusion to those attempting to migrate from the legacy Tiered architecture.

Also there should be notes regarding licensing requirements.

Lastly, this document focuses on PAWs and user access workstations. What guidance is there to seamlessly incorporate Tier 1(Server) and Tier 2( Domain controllers, ADFS servers, Certificate) services in the cloud and on-prem into this model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc109e7-e2ad-6e3c-598d-36876b40dbfd
* Version Independent ID: da56e91b-41ca-2c29-0e8c-bc4d2a36a748
* Content: [Deploying a privileged access solution](https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment)
* Content Source: [compass/privileged-access-deployment.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-deployment.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
