### ISSUE TITLE
add -online switch to get-windowsautopilotinfo section

### ISSUE THREAD

**Issue by dnevelos** [MicrosoftDocs/security#35]
Update Get-WindowsAutopilotinfo script section to include the -online option which allows bypass of USB/CSV upload. 

https://oofhours.com/2020/03/25/importing-a-device-hash-directly-into-intune/

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc109e7-e2ad-6e3c-598d-36876b40dbfd
* Version Independent ID: da56e91b-41ca-2c29-0e8c-bc4d2a36a748
* Content: [Deploying a privileged access solution](https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment)
* Content Source: [compass/privileged-access-deployment.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-deployment.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
