### ISSUE TITLE
Clarification on what is meant by NotBefore

### ISSUE THREAD

**Issue by afatsoum** [MicrosoftDocs/security#37]
Hi Karina,

Can you clarify the language for the following?

- This release will NotBefore the following roots
- This release will NotBefore the TLS EKUs to the following roots
- This release will NotBefore the Code Signing EKUs to the following roots

i.e. What does it mean that the release will NotBefore the Code Signing EKU for those selected roots?

Question(s):

1. Does it mean that files that are signed by certificates that are chained to these roots will no longer be trusted for Code Signing?
2. Similar to the first question, files signed using the same hierarchy before the release date will still be trusted/valid?
3. Does this specifically impact only the files that are signed after the Feb2021 release date?
4. Can you share the exact date this went into effect?
5. Is there a way for organizations to opt-out or temporarily allow trust back for these roots CodeSigning EKU?

thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7947fabb-68cf-53f1-938b-9d058a5b5fe8
* Version Independent ID: 41c00c20-ce22-1eb1-f830-d1d55c0ba466
* Content: [February 2021 Deployment Notice - Microsoft Trusted Root Program](https://docs.microsoft.com/en-us/security/trusted-root/2021/feb2021)
* Content Source: [trusted-root-docs/2021/Feb2021.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/2021/Feb2021.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
