### ISSUE TITLE
Good Document!!!!

### ISSUE THREAD

**Issue by LuisHernandezNJ** [MicrosoftDocs/security#39]
Nicely done!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 624b3329-cc27-fe94-e6ed-d13ef4f659b2
* Version Independent ID: d603f3e6-bb85-ff8f-d639-415b2b149a6d
* Content: [Zero Trust Guidance Center](https://docs.microsoft.com/en-us/security/zero-trust/)
* Content Source: [zero-trust/index.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/index.md)
* Service: **security**
* GitHub Login: @garycentric
* Microsoft Alias: **v-gmoor**

**Comment by knicholasa** [comment]
Thank you for the positive feedback! :)
