### ISSUE TITLE
Incorrect title on ZT for secure applications

### ISSUE THREAD

**Issue by gigabit-jack** [MicrosoftDocs/security#41]
This page has an incorrect title. Instead of "**Secure applications with Zero Trust | Microsoft Docs**" it shows as, "**Audit Requirements - Microsoft Trusted Root Certificate Program | Microsoft Docs**"

Screenshot for reference:
![image](https://user-images.githubusercontent.com/65245638/125547561-98ffce22-5333-4a52-aecd-3ebfc3ce5b45.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a543f3e8-ff01-6b86-4346-ae612e34e017
* Version Independent ID: 498437e8-c0bd-d5b3-e0e4-4817febee92d
* Content: [Audit Requirements - Microsoft Trusted Root Certificate Program](https://docs.microsoft.com/en-us/security/zero-trust/applications)
* Content Source: [zero-trust/applications.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/applications.md)
* Service: **security**
* GitHub Login: @Kellylorenebaker
* Microsoft Alias: **v-kbaker**

**Comment by knicholasa** [comment]
Thanks for catching this, the title has been updated.
