### ISSUE TITLE
Conditonal Access policy does not enforce specific device

### ISSUE THREAD

**Issue by strav970** [MicrosoftDocs/security#42]
One of the biggest challenges we have faced when trying to extrapolate the PAW model to Cloud Management is the inability of Azure AD to require specific devices. The CA policy outlined here requires Compliant Devices, but nothing stops the Privileged Cloud Admin from performing sign in from a less secure still compliant device.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc109e7-e2ad-6e3c-598d-36876b40dbfd
* Version Independent ID: da56e91b-41ca-2c29-0e8c-bc4d2a36a748
* Content: [Deploying a privileged access solution](https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment)
* Content Source: [compass/privileged-access-deployment.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-deployment.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by MicrosoftGuyJFlo** [comment]
Content is being updated to include the use of Filters for devices. This currently preview feature will help with that case
