### ISSUE TITLE
Disable Legacy TLS - Not implemented

### ISSUE THREAD

**Issue by adixon25** [MicrosoftDocs/security#47]
This function does not appear to be implemented in Windows Server 2019 at the current time despite what is indicated in this article.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cec334a9-609f-3f33-0aec-da9fdcd3ef3a
* Version Independent ID: 40577249-582c-85e9-c7dc-e4cd6c700fa7
* Content: [TLS version enforcement capabilities now available per certificate binding on Windows Server 2019 - Security documentation](https://docs.microsoft.com/en-us/security/engineering/disable-legacy-tls)
* Content Source: [security-docs/engineering/Disable-Legacy-TLS.md](https://github.com/MicrosoftDocs/security/blob/main/security-docs/engineering/Disable-Legacy-TLS.md)
* Product: **security**
* GitHub Login: @amarshal
* Microsoft Alias: **AMarshal**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
