### ISSUE TITLE
FIDO2 Security Key Partner Application Delayed

### ISSUE THREAD

**Issue by LinVince** [MicrosoftDocs/security#49]
Hi Microsoft, 

Following #24 

Matt has replied and we have signed the NDA... 
But it seems that we have not got any feedback for months... and he didn't reply email

Is it possible to check the progress. I would really appreciate it.

Vince

**Comment by knicholasa** [comment]
Hi Vince, 

Apologies for the delay. I checked with Matt and it sounds like you have been able to get in touch. I will close this issue. 

Thanks
Nick
