### ISSUE TITLE
Inaccurate Bibliography 

### ISSUE THREAD

**Issue by ebishoff** [MicrosoftDocs/security#5]
Citations are off on this page. For example, the model inversion example citation should be 5 not 4. I noticed that there were a few others that seemed off.. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31b68761-d591-2cdf-ddec-5746b4a13a1b
* Version Independent ID: d5149a4f-deb2-22df-2863-044b0af35022
* Content: [Threat Modeling AI/ML Systems and Dependencies - Security documentation](https://docs.microsoft.com/en-us/security/engineering/threat-modeling-aiml)
* Content Source: [security-docs/engineering/Threat-modeling-aiml.md](https://github.com/MicrosoftDocs/security/blob/main/security-docs/engineering/Threat-modeling-aiml.md)
* Product: **security**
* GitHub Login: @amarshal
* Microsoft Alias: **AMarshal**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. This issue appears to be fixed. #please-close
