### ISSUE TITLE
Data section diagram is actually the one from the Identity section

### ISSUE THREAD

**Issue by dlRo** [MicrosoftDocs/security#51]
https://docs.microsoft.com/en-us/security/zero-trust/data / Traditional data security objectives section:

This is diagram is actually taken from the Identity section, I'm sure not the one intended for this section.
![Screenshot 2021-08-01 222008](https://user-images.githubusercontent.com/34405064/127796134-3252c5b8-5ddf-4f76-a328-5bf3f67c77cf.jpg)

**Comment by knicholasa** [comment]
Thank you for catching this! I am opening a PR to replace with the correct image.
