### ISSUE TITLE
Video link may be wrong for "Part 6: Build an Identity Perimeter"

### ISSUE THREAD

**Issue by ryukiy** [MicrosoftDocs/security#55]
[Enter feedback here]
Video link for "Part 6: Build an Identity Perimeter" is the same as link for "Part 4: Account Security: Measuring Cost of Attack Password-less Authentication".
I suspect there is a correct link for "Part 6: Build an Identity Perimeter".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4226cb9-a80f-aff5-95e8-ef73bc4c7ddc
* Version Independent ID: de7d413b-9f5c-dafc-10b1-a750e6820f91
* Content: [Chief Information Security Officer (CISO) Workshop, Module 3:Identity, and Access Management - Security documentation](https://docs.microsoft.com/en-us/security/ciso-workshop/ciso-workshop-module-3)
* Content Source: [ciso-workshop/ciso-workshop-module-3.md](https://github.com/MicrosoftDocs/security/blob/main/ciso-workshop/ciso-workshop-module-3.md)
* Service: **o365-seccomp**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
@MicrosoftGuyJFlo , @MarkSimos - This Issue is old but still true. Please review and fix if appropriate. Thanks!

**Comment by MicrosoftGuyJFlo** [comment]
#please-close

Found the correct video and updated the link
