### ISSUE TITLE
Part 6: Build an Identity Perimeter video is wrongly linked

### ISSUE THREAD

**Issue by MarekLani** [MicrosoftDocs/security#56]
Part 6: Build an Identity Perimeter (13:57) on this page is referencing wrong video (Credentials Security instead of building identity perimeter)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4226cb9-a80f-aff5-95e8-ef73bc4c7ddc
* Version Independent ID: de7d413b-9f5c-dafc-10b1-a750e6820f91
* Content: [Chief Information Security Officer (CISO) Workshop, Module 3:Identity, and Access Management - Security documentation](https://docs.microsoft.com/en-us/security/ciso-workshop/ciso-workshop-module-3?view=o365-worldwide)
* Content Source: [ciso-workshop/ciso-workshop-module-3.md](https://github.com/MicrosoftDocs/security/blob/main/ciso-workshop/ciso-workshop-module-3.md)
* Service: **o365-seccomp**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
@MicrosoftGuyJFlo , @MarkSimos - This issue is old but still true. Please fix if appropriate. Thanks!

**Comment by MicrosoftGuyJFlo** [comment]
@TerryLanfear Found the video and resolving in PR 1162 later today.

@MarekLani Sorry for how long it took to resolve this.

**Comment by MicrosoftGuyJFlo** [comment]
#please-close
