### ISSUE TITLE
Iterative diagram at top of page does not work with dark theme

### ISSUE THREAD

**Issue by alistairl** [MicrosoftDocs/security#57]
The circular process diagram at the top of the Infrastructure page disappears on a dark theme browser as the text is dark.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 59f88625-7e6f-708b-7f7f-d6017db8f593
* Version Independent ID: eb3699f9-5527-e560-f9f9-82ba402f17fe
* Content: [Securing infrastructure with Zero Trust](https://docs.microsoft.com/en-gb/security/zero-trust/infrastructure)
* Content Source: [zero-trust/infrastructure.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/infrastructure.md)
* Service: **security**
* GitHub Login: @Kellylorenebaker
* Microsoft Alias: **v-kbaker**

**Comment by knicholasa** [comment]
You're right. I'm replacing it with an image with a white background to fix this. Thanks!

**Comment by alistairl** [comment]
Looking good in Edge Chromium, thanks for the change.
