### ISSUE TITLE
Broken link to application form

### ISSUE THREAD

**Issue by Crypt32** [MicrosoftDocs/security#6]
The document contains a link to application form (https://aka.ms/rootcertapply), however, it points to a generic page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a89d1f2-b584-a6ce-711e-45a84b9efd0e
* Version Independent ID: 09b2b395-f083-dd0b-8113-95c90701814d
* Content: [Program Requirements - Microsoft Trusted Root Program](https://docs.microsoft.com/en-us/security/trusted-root/new-ca-application)
* Content Source: [trusted-root-docs/new-ca-application.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/new-ca-application.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by kasirota** [comment]
We will be updating this in our upcoming program requirements release.

**Comment by Crypt32** [comment]
@TerryLanfear this isn't fixed yet, the URL points to 404 now.

**Comment by TerryLanfear** [comment]
@Crypt32 - Thank you for the feedback. I'm looking into this now.

**Comment by tahmad2** [comment]
#please-close
