### ISSUE TITLE
privileged access deployment has inconsistent naming in AAD section

### ISSUE THREAD

**Issue by markwahl-msft** [MicrosoftDocs/security#62]
Hi, the privileged-access-deployment.md section ## Azure Active Directory configuration there was some unusual or inconsistent naming of the users and groups

First, there are two users with the same name.

Line 42 has creating a user 
```
   * **Name** - Secure Workstation Administrator
```
line 53 has creating another user
```
   * **Name** - Secure Workstation Administrator
```
Second, line 45 has setting a usage location for the first user, but the second user doesn't have a usage location.  Is that significant?

Third, line 59 mentions four groups, none of which have Privileged in their name.  Line 73 says "For the Privileged Workstation Admins group" and then gives the group name as "Secure Workstation Admins". Might want to clarify if the Privileged Workstations are the same as the Secure Workstations, or if different.

Finally, a minor nit - line 95 has a 
```
(device.devicePhysicalIds -any _ -contains "[OrderID]:PAW")
```
but other documents, e.g., https://docs.microsoft.com/en-us/mem/autopilot/enrollment-autopilot have an additional level of parenthesis, as in
```
(device.devicePhysicalIds -any (_ -eq "[OrderID]:179887111881"))
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc109e7-e2ad-6e3c-598d-36876b40dbfd
* Version Independent ID: da56e91b-41ca-2c29-0e8c-bc4d2a36a748
* Content: [Deploying a privileged access solution](https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment)
* Content Source: [compass/privileged-access-deployment.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-deployment.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
