### ISSUE TITLE
Cannot open the link https://aka.ms/rootcertapply

### ISSUE THREAD

**Issue by stanimirakostova** [MicrosoftDocs/security#66]
[Enter feedback here]

Cannot open the link https://aka.ms/rootcertapply listed here. Can you please help us? 

Certificate Authority Intake Process
An applicant CA must fill out the application located at https://aka.ms/rootcertapply and email the completed form to [msroot@microsoft.com]. This will add the CA to a queue of applications that will be reviewed in order of initial application time.

https://docs.microsoft.com/en-us/security/trusted-root/new-ca-application

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a89d1f2-b584-a6ce-711e-45a84b9efd0e
* Version Independent ID: 09b2b395-f083-dd0b-8113-95c90701814d
* Content: [Program Requirements - Microsoft Trusted Root Program](https://docs.microsoft.com/en-us/security/trusted-root/new-ca-application)
* Content Source: [trusted-root-docs/new-ca-application.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/new-ca-application.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by TerryLanfear** [comment]
@kasirota - please fix the broken link.

**Comment by tahmad2** [comment]
#please-close
