### ISSUE TITLE
Microsoft Trusted Root Program, Certificate Authority Intake Application Not Available.

### ISSUE THREAD

**Issue by sachithraswg** [MicrosoftDocs/security#7]
The link (https://aka.ms/rootcertapply) which is mention in the article "Microsoft Trusted Root Program -> Certificate Authority Intake Process" (https://docs.microsoft.com/en-us/security/trusted-root/new-ca-application) is not working.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a89d1f2-b584-a6ce-711e-45a84b9efd0e
* Version Independent ID: 09b2b395-f083-dd0b-8113-95c90701814d
* Content: [Program Requirements - Microsoft Trusted Root Program](https://docs.microsoft.com/en-us/security/trusted-root/new-ca-application)
* Content Source: [trusted-root-docs/new-ca-application.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/new-ca-application.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by kasirota** [comment]
We will be updating this in our upcoming program requirements release.
