### ISSUE TITLE
Formatting issue in the Bug Bar security documentation

### ISSUE THREAD

**Issue by S-Callier** [MicrosoftDocs/security#72]
Thanks for sharing all that SDL related content.

The formatting seems to be broken in the linked document around those sentences:

**Critical.** *A security vulnerability that would be rated as having the highest potential for damage.*
**Important.** *A security vulnerability that would be rated as having significant potential for damage, but less than Critical.*
**Moderate.** *A security vulnerability that would be rated as having moderate potential for damage, but less than Important.*
**Low.** *A security vulnerability that would be rated as having low potential for damage.*

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b0b00ce-6512-4b37-ecc6-9767862df528
* Version Independent ID: 27ac40bd-2ae0-76ff-1297-6126e0fabd07
* Content: [SDL Security Bug Bar (Sample) - Security Documentation](https://docs.microsoft.com/en-us/security/sdl/security-bug-bar-sample)
* Content Source: [security-docs/SDL/Security-Bug-Bar-sample.md](https://github.com/MicrosoftDocs/security/blob/main/security-docs/SDL/Security-Bug-Bar-sample.md)
* Service: **security**
* GitHub Login: @BruceCowper
* Microsoft Alias: **bcowper**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
