### ISSUE TITLE
Duplicate video for part 4 and part 6 of the workshop

### ISSUE THREAD

**Issue by ghost** [MicrosoftDocs/security#76]
"Part 4: Account Security: Measuring Cost of Attack Password-less Authentication (13:11)" and "Part 6: Build an Identity Perimeter (13:57)" use the same video, which does not seem correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a4226cb9-a80f-aff5-95e8-ef73bc4c7ddc
* Version Independent ID: de7d413b-9f5c-dafc-10b1-a750e6820f91
* Content: [Chief Information Security Officer (CISO) Workshop, Module 3:Identity, and Access Management - Security documentation](https://docs.microsoft.com/en-us/security/ciso-workshop/ciso-workshop-module-3?view=o365-worldwide)
* Content Source: [ciso-workshop/ciso-workshop-module-3.md](https://github.com/MicrosoftDocs/security/blob/main/ciso-workshop/ciso-workshop-module-3.md)
* Service: **o365-seccomp**
* GitHub Login: @Dansimp
* Microsoft Alias: **dansimp**

**Comment by TerryLanfear** [comment]
Thank you for your interest in our documentation. This issue was fixed via https://github.com/MicrosoftDocs/security/issues/55.

#please-close
