### ISSUE TITLE
Link broken: "Don’t synchronize on-premises admin accounts to cloud identity providers" 

### ISSUE THREAD

**Issue by diecknet** [MicrosoftDocs/security#77]
The link "Don’t synchronize on-premises admin accounts to cloud identity providers" is broken
```
[Don’t synchronize on-premises admin accounts to cloud identity providers](/azure/architecture/security/identity#dont-synchronize-on-premises-admin-accounts-to-cloud-identity-providers)
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01170a31-4528-5f61-2148-ddb747a9ac5c
* Version Independent ID: 40fdb01e-0b92-f95c-6227-408129394071
* Content: [Administration in Azure](https://docs.microsoft.com/en-us/security/compass/critical-impact-accounts)
* Content Source: [compass/critical-impact-accounts.md](https://github.com/MicrosoftDocs/security/blob/main/compass/critical-impact-accounts.md)
* Service: **security**
* Sub-service: **cloud-design-principles**
* GitHub Login: @MarkSimos

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears that this issue is fixed. #please-close
