### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by mw8er** [MicrosoftDocs/security#79]
Hi there,

there is a broken link in the section [Finish workstation profile hardening](
https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment#finish-workstation-profile-hardening)

It seems like the row for **Enterprise** is broken and this is breaking the link.

Best regards,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fc109e7-e2ad-6e3c-598d-36876b40dbfd
* Version Independent ID: da56e91b-41ca-2c29-0e8c-bc4d2a36a748
* Content: [Deploying a privileged access solution](https://docs.microsoft.com/en-us/security/compass/privileged-access-deployment#finish-workstation-profile-hardening)
* Content Source: [compass/privileged-access-deployment.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-deployment.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears that this issue is now fixed. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
