### ISSUE TITLE
Playbooks seems like a poor use of words

### ISSUE THREAD

**Issue by AndrewBlumhardt** [MicrosoftDocs/security#8]
[Enter feedback here]
Playbooks seems like a poor use of words when you consider that Logic Apps are also called playbooks in Sentinel.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daae9c8b-a9c6-01a7-1072-faaab97793bf
* Version Independent ID: 08cb659e-3295-e2df-4d9b-e0f426e238e7
* Content: [Phishing investigation](https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-phishing)
* Content Source: [compass/incident-response-playbook-phishing.md](https://github.com/MicrosoftDocs/security/blob/main/compass/incident-response-playbook-phishing.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by JoeDavies-MSFT** [comment]
@AndrewBlumhardt Hi, Andrew. The term playbooks is commonly used in the cybersecurity community. Azure Logic Apps are used to create Azure Sentinel playbooks. See https://docs.microsoft.com/en-us/azure/sentinel/automate-responses-with-playbooks. In my next refresh, I'll add a mention and link to the Azure article above.

Thanks for your feedback.
