### ISSUE TITLE
Zero trus

### ISSUE THREAD

**Issue by GajuOSCP** [MicrosoftDocs/security#83]
[proper way from zero trust ]

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 624b3329-cc27-fe94-e6ed-d13ef4f659b2
* Version Independent ID: d603f3e6-bb85-ff8f-d639-415b2b149a6d
* Content: [Zero Trust Guidance Center](https://docs.microsoft.com/en-gb/security/zero-trust/)
* Content Source: [zero-trust/index.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/index.md)
* Service: **security**
* GitHub Login: @garycentric
* Microsoft Alias: **v-gmoor**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
