### ISSUE TITLE
A link in the page does work

### ISSUE THREAD

**Issue by calvini-03** [MicrosoftDocs/security#84]
This is a good article but is has a couple of things missing. First, there are not references to Privileged Access Workstation links. 

Second, the following link doesn't work
https://docs.microsoft.com/en-us/azure/architecture/security/identity#dont-synchronize-on-premises-admin-accounts-to-cloud-identity-providers

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 01170a31-4528-5f61-2148-ddb747a9ac5c
* Version Independent ID: 40fdb01e-0b92-f95c-6227-408129394071
* Content: [Administration in Azure](https://docs.microsoft.com/en-us/security/compass/critical-impact-accounts)
* Content Source: [compass/critical-impact-accounts.md](https://github.com/MicrosoftDocs/security/blob/main/compass/critical-impact-accounts.md)
* Service: **security**
* Sub-service: **cloud-design-principles**
* GitHub Login: @MarkSimos

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
