### ISSUE TITLE
PLANE/PLAN

### ISSUE THREAD

**Issue by TJCS78** [MicrosoftDocs/security#85]
[DATA PLAN ( DATA PLANE )]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a389c058-7fcf-c61f-dfc4-9ce4521238ce
* Version Independent ID: 57b1cf2e-5b2a-3124-b650-77e1b4e01f1a
* Content: [Securing privileged access Enterprise access model](https://docs.microsoft.com/en-us/security/compass/privileged-access-access-model)
* Content Source: [compass/privileged-access-access-model.md](https://github.com/MicrosoftDocs/security/blob/main/compass/privileged-access-access-model.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
