### ISSUE TITLE
Application to enroll not available on this page

### ISSUE THREAD

**Issue by Anthonymattocks** [MicrosoftDocs/security#88]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1db021c-1d09-d455-f2b7-e417844ccc85
* Version Independent ID: 9f469880-6a23-71e4-d728-8bf7b05bb8e7
* Content: [Program Requirements - Microsoft Trusted Root Program](https://docs.microsoft.com/en-us/security/trusted-root/program-requirements)
* Content Source: [trusted-root-docs/Program-Requirements.md](https://github.com/MicrosoftDocs/security/blob/main/trusted-root-docs/Program-Requirements.md)
* Service: **security**
* GitHub Login: @kasirota
* Microsoft Alias: **kasirota**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
