### ISSUE TITLE
Search-mailbox is deprecated

### ISSUE THREAD

**Issue by warrenstark** [MicrosoftDocs/security#9]
Refer - https://docs.microsoft.com/en-us/powershell/module/exchange/search-mailbox?view=exchange-ps

Guidance should include how to use the compliance search cmdlets now. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: daae9c8b-a9c6-01a7-1072-faaab97793bf
* Version Independent ID: 08cb659e-3295-e2df-4d9b-e0f426e238e7
* Content: [Phishing investigation](https://docs.microsoft.com/en-us/security/compass/incident-response-playbook-phishing)
* Content Source: [compass/incident-response-playbook-phishing.md](https://github.com/MicrosoftDocs/security/blob/main/compass/incident-response-playbook-phishing.md)
* Product: **m365-security**
* Technology: **m365d**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. This issue appears to be fixed. #please-close
