### ISSUE TITLE
Issue - please fix dead link 

### ISSUE THREAD

**Issue by amanjeetsingh** [MicrosoftDocs/security#90]
The hyperlink for **Best Practices** doesn't work and throws up error 404. Either the page has moved or hyerplink is incorrect. 

**Problem hyperlink**
https://docs.microsoft.com/en-us/azure/architecture/framework/security/critical-impact-accounts

![image](https://user-images.githubusercontent.com/7122931/152234559-1f68075d-9efb-4b1e-b173-b3eff6a3f422.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dfc42b40-dd9b-e70b-bdb2-b5e7d04f2923
* Version Independent ID: f424e6b3-70b4-17f7-744f-0e0967388cbc
* Content: [Securing privileged access overview](https://docs.microsoft.com/en-us/security/compass/overview)
* Content Source: [compass/overview.md](https://github.com/MicrosoftDocs/security/blob/main/compass/overview.md)
* Service: **security**
* Sub-service: ****
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears this issue has been fixed. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
