### ISSUE TITLE
Wording "Identify" for "Identity"

### ISSUE THREAD

**Issue by TJCS78** [MicrosoftDocs/security#93]
https://docs.microsoft.com/en-us/learn/modules/audit-identity-access-management/tools-technologies-used

 Device health checks complement other access controls, including IP restrictions, IPsec policies, and user identify verification through multi-factor authentication. 

"Identify verification" for "Identity verification" in the sentence.

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
