### ISSUE TITLE
wrong header

### ISSUE THREAD

**Issue by gitralf** [MicrosoftDocs/security#95]
The header "Alert and Log Ingestion" is wrong and should be "Alert and Log Integration" as you can see from 00:22 in the video

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cee46b0b-ac67-ac24-7a47-8ed7ab1a4f79
* Version Independent ID: 832a4d07-7564-3bfb-5b21-8544d79b6469
* Content: [Microsoft Security Best Practices module: Security operations](https://docs.microsoft.com/en-us/security/compass/security-operations-videos-and-decks)
* Content Source: [compass/security-operations-videos-and-decks.md](https://github.com/MicrosoftDocs/security/blob/main/compass/security-operations-videos-and-decks.md)
* Product: **m365-security**
* GitHub Login: @JoeDavies-MSFT
* Microsoft Alias: **josephd**

**Comment by TerryLanfear** [comment]
@MicrosoftGuyJFlo - Please review. This issue still exists. Thanks!

**Comment by MicrosoftGuyJFlo** [comment]
#please-close Resolved in linked PR. Thank you!

**Comment by TerryLanfear** [comment]
@gitralf  - Thanks for your dedication to our documentation.
