### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by danielDMP** [MicrosoftDocs/security#96]
"See [Centralize Network Management And Security](https://docs.microsoft.com/en-us/azure/architecture/security/network-security-containment#centralize-network-management-and-security) for more details"

The link is not valid (404): https://docs.microsoft.com/en-us/azure/architecture/security/network-security-containment#centralize-network-management-and-security

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3741e6b9-d5d4-7164-ce67-732a9e4f92f3
* Version Independent ID: ba54bf5b-2320-d7c5-f90f-c5c4651cc9eb
* Content: [Governance, risk, and compliance in Azure](https://docs.microsoft.com/en-us/security/compass/governance#core-services-reference-permissions)
* Content Source: [compass/governance.md](https://github.com/MicrosoftDocs/security/blob/main/compass/governance.md)
* Service: **security**
* Sub-service: **cloud-design-principles**
* GitHub Login: @MarkSimos

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. It appears this issue is now fixed. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
