### ISSUE TITLE
On-premises not on-premise

### ISSUE THREAD

**Issue by robm82** [MicrosoftDocs/security#98]
Small typo in the paragraph here: https://docs.microsoft.com/en-us/security/zero-trust/deploy/data#automatically-classify-label-and-protect-business-critical-content-with-sensitive-data-on-premises

It should be "on-premises" not "on-premise" 🙂

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 79343709-0480-e6d0-bf6f-71d36cd24eb3
* Version Independent ID: 05216694-6a9c-6971-419f-ec134a954e58
* Content: [Secure data with Zero Trust](https://docs.microsoft.com/en-us/security/zero-trust/deploy/data)
* Content Source: [zero-trust/deploy/data.md](https://github.com/MicrosoftDocs/security/blob/main/zero-trust/deploy/data.md)
* Service: **security**
* GitHub Login: @garycentric
* Microsoft Alias: **v-gmoor**

**Comment by cabailey** [comment]
I don't see any references to "on-premise" so assume this must now be fixed & the issue can be closed
#please-close
