### ISSUE TITLE
Two sections in #5 Model Stealing are unclear.

### ISSUE THREAD

**Issue by Crilliant** [MicrosoftDocs/security#99]
The description in "Traditional Parallels" is like : "Unauthenticated, read-only tampering of system data, targeted high-value information disclosure?" Its expression confuses me. 
    The description in "Severity" is :"Important in security-sensitive models, Moderate otherwise" It is clear that something is missing. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31b68761-d591-2cdf-ddec-5746b4a13a1b
* Version Independent ID: d5149a4f-deb2-22df-2863-044b0af35022
* Content: [Threat Modeling AI/ML Systems and Dependencies - Security documentation](https://docs.microsoft.com/en-us/security/engineering/threat-modeling-aiml#5-model-stealing)
* Content Source: [security-docs/engineering/Threat-modeling-aiml.md](https://github.com/MicrosoftDocs/security/blob/main/security-docs/engineering/Threat-modeling-aiml.md)
* Product: **security**
* GitHub Login: @amarshal
* Microsoft Alias: **AMarshal**

**Comment by TerryLanfear** [comment]
Thanks for your dedication to our documentation. Unfortunately, at this time we have been unable to review your issue in a timely manner and we sincerely apologize for the delayed response. We are closing this issue for now, but if you feel that it's still a concern, please respond and let us know. If you determine another possible update to our documentation, please don't hesitate to reach out again. #please-close
